### ISSUE TITLE
Validation failed while installing

### ISSUE THREAD

**Issue by haribole** [cloudflare/helm-charts#17]
Hello

I am getting the following error when installing:

helm install --name test -n testns --set rbac.create=true --set controller.ingressClass=argo-tunnel --set controller.logLevel=6 cloudflare/argo-tunnel --debug

[debug] Created tunnel using local port: '41079'
[debug] SERVER: "127.0.0.1:41079"
[debug] Original chart version: ""
[debug] Fetched cloudflare/argo-tunnel to /home/smx/.helm/cache/archive/argo-tunnel-0.6.5.tgz
[debug] CHART PATH: /home/smx/.helm/cache/archive/argo-tunnel-0.6.5.tgz

Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by MilanDasek** [comment]
any news here?

**Comment by leighporter** [comment]
> any news here?

Well..  Stuff the error into google and it seems related to API changes in v1.16.

**Comment by MilanDasek** [comment]
Yes that is clear - this has to be changed `apps/v1`

**Comment by gangsta** [comment]
temporary you can use this https://gist.github.com/gangsta/8c555fe73f24ba0300b3b18914f4c653
