### ISSUE TITLE
using old apiVersion: extensions/v1beta1 Deployment resource definition

### ISSUE THREAD

**Issue by zeph** [cloudflare/helm-charts#22]
which has been deprecated since Kubernetes 1.16
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by manchuwook** [comment]
I'm running into this as well - using Microk8s on Ubuntu 20.04.

**Comment by gajus** [comment]
The install is now failing. :-(

**Comment by AlecDusheck** [comment]
There are multiple PRs for this but the Cloudflare folks don't seem maintain this repo (even though its critical for a big product they offer). A shame, honestly.

**Comment by kusanagi-jin** [comment]
I encountered the same problem. I tried to follow the official document for this https://developers.cloudflare.com/argo-tunnel/reference/kubernetes

**Comment by AlecDusheck** [comment]
The k8 version of Argo seems to be deprecated (even though it isn't mentioned on Github). You should use Argo in a sidecar instead.

**Comment by gangsta** [comment]
as temporary use this https://gist.github.com/gangsta/8c555fe73f24ba0300b3b18914f4c653

**Comment by stearz** [comment]
The workaround is not working for us. Is there a chance that we get this PR merged soon?
https://github.com/cloudflare/helm-charts/pull/21

**Comment by gangsta** [comment]
This Helm-charts is going to be depreciated, I believe you should start looking into

https://blog.cloudflare.com/argo-tunnels-that-live-forever/
https://github.com/cloudflare/argo-tunnel-examples/tree/master/named-tunnel-k8s
https://developers.cloudflare.com/argo-tunnel/configuration/ingress
