### ISSUE TITLE
Difference between cloudflare-tunnel and cloudflare-tunnel-remote?

### ISSUE THREAD

**Issue by verenion** [cloudflare/helm-charts#46]
I see there are now two helm-charts in this repo. 

cloudflare-tunnel doesn't seem to manage the public hostnames in cloudflare automatically, which means they have to be managed remotely anyway.

cloudflare-tunnel-remote simply errors with: 

```
rror: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].envFrom[0].secretRef): unknown field "key" in io.k8s.api.core.v1.SecretEnvSource
```

Some aadditional documentation on how these are used and if these charts are ready for production use would be great.

**Comment by uhthomas** [comment]
I am pretty sure the cloudflare-tunnel-remote chart is for [remotely managed tunnels](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/install-and-setup/tunnel-guide/remote/remote-management/).

It does look like the chart is broken though, it is not valid to specify an individual secret key for `envFrom`.

**Comment by denzhel** [comment]
Please merge the fix for this issue <3
